ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("store.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path("", views.home, name="home"),
    path("store", views.store, name="store"),
    path("store/products/<int:pk>", views.product_detail, name="product_detail"),
    path("cart", views.cart, name="cart"),
    path("checkout", views.checkout, name="checkout"),
    path("update_item", views.updateItem, name="update_item"),
    path("process_order", views.processOrder, name="process_order")
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE, related_name="customer")
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(default="placeholder.png", blank=True)
    description= models.TextField(null=True, blank=True)
    additional_info = models.TextField(null=True, blank=True)
    sub_image1 = models.ImageField(null=True, blank=True)
    sub_image2 = models.ImageField(null=True, blank=True)
    sub_image3 = models.ImageField(null=True, blank=True)


    def __str__(self):
        return self.name

    @property
    def other_images(self):
        if(self.sub_image1 or self.sub_image2 or self.sub_image3):
            return True
        else: 
            return False

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True, related_name="orders")
    date_ordered = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False, blank=True, null=True)
    transaction_id = models.CharField(max_length=200, null=True)

    @property
    def get_total_items(self):
        order_items = self.order_items.all()
        total = sum([item.quantity for item in order_items])
        return total

    @property
    def get_total_price(self):
        order_items = self.order_items.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def shipping(self):
        order_items = self.order_items.all()
        shipping = False
        for item in order_items:
            if item.product.digital == False:
                shipping = True
        return shipping

    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, related_name="order_items")
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL, related_name="order_items")
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL, related_name="address")
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL, related_name="address")
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
import json
from .models import *
import datetime
from .utils import cartData, cookieCart, guestOrder

# Create your views here.
def home(request):
    products = Product.objects.all()[:6]
    context = {"products": products}
    return render(request, "store/home.html", context)

def product_detail(request, pk):
    # return HttpResponse("This is the detials page")
    data = cartData(request)
    cart_items = data["cart_items"]
    product = get_object_or_404(Product, pk=pk)
    context = {"product": product, "cart_items": cart_items}
    return render(request, "store/product_detail.html", context)

def store(request):
    data = cartData(request)
    cart_items = data["cart_items"]
 
    products = Product.objects.all()
    context = {"products": products, "cart_items": cart_items}
    return render(request, "store/store.html", context)

def cart(request):
    data = cartData(request)
    items = data["items"]
    order = data["order"]
    cart_items = data["cart_items"]
    context = {"items": items, "order": order, "cart_items": cart_items}
    return render(request, "store/cart.html", context)

def main(request):
    context = {}
    return render(request, "store/main.html", context)

def checkout(request):
    data = cartData(request)
    items = data["items"]
    order = data["order"]
    cart_items = data["cart_items"]
    context = {"items": items, "order": order, "cart_items": cart_items}
    return render(request, "store/checkout.html", context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data["productId"]
    action = data["action"]
    # print("Action: " + action)
    # print("productId: " + productId)
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, completed=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    print(created)
    if action == "add":
        orderItem.quantity = orderItem.quantity + 1
    elif action == "remove":
        orderItem.quantity = orderItem.quantity - 1
    orderItem.save()
    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse("item was added", safe=False)

def processOrder(request):
    # print(json.loads(request.body))
    data = json.loads(request.body)
    transaction_id = datetime.datetime.now().timestamp()

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, completed=False)
        
        if order.shipping == True:
            ShippingAddress.objects.create(
                customer = customer,
                order = order,
                address = data["shipping"]["address"],
                city = data["shipping"]["city"],
                state = data["shipping"]["state"],
                zipcode = data["shipping"]["zipcode"],
            )
    else:
        customer, order = guestOrder(request, data)

    total = float(data["form"]["total"])
    order.transaction_id = transaction_id
    # print(total == order.get_total_items())
    if total == order.get_total_items:
        order.completed = True
    order.save()
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data["shipping"]["address"],
            city = data["shipping"]["city"],
            state = data["shipping"]["state"],
            zipcode = data["shipping"]["zipcode"],
        )

    return JsonResponse("Payment complete", safe=False)

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<h1 class="text-success text-center">Cart</h1>
<div class="row">
    <div class="col-md-12">
        <div class="shadow-lg">
            <a href="#" class="btn btn-outline-dark">&#x2190; continue shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>{{ order.get_total_items }}</strong></h5></th>
                    <th><h5>Total: <strong>${{ order.get_total_price|floatformat:2 }}</strong></h5></th>
                    <th>
                        <a href="{% url 'store:checkout' %}" class="btn btn-success float-right m-3">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>
        <div class="shadow">
            <div class="d-flex pb-2 mb-2 border-bottoms">
                <div style="flex:2;"></div>
                <div style="flex:2;"><p>Item</p></div>
                <div style="flex:1;"><p>Price</p></div>
                <div style="flex:1;"><p>Quantity</p></div>
                <div style="flex:1;"><p>Total</p></div>
            </div>
            {% for item in items %}
            <div class="d-flex pb-2 mb-2 border-bottoms">
                <div style="flex:2;"><img width="70px" src="{{ item.product.image.url }}" alt="Placeholder"></div>
                <div style="flex:2;"><p>{{ item.product.name }}</p></div>
                <div style="flex:1;"><p>${{ item.product.price|floatformat:2 }}</p></div>
                <div style="flex:1;" class="">
                    <p class="d-inline-block mr-2">{{ item.quantity }}</p>
                    <div class="d-inline-block">
                        <img width="12px" data-product="{{ item.product.id }}" data-action="add" class="d-block mt-1 update-cart" src="{% static 'images/arrow-up.png' %}" alt="arrow up">
                        <img width="12px" data-product="{{ item.product.id }}" data-action="remove" class="d-block mt-1 update-cart" src="{% static 'images/arrow-down.png' %}" alt="arrow down">
                    </div>
                </div>
                <div style="flex:1;"><p>${{ item.get_total }}</p></div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<!-- <h1 class="text-success">Checkout</h1> -->
<div class="row py-5">
    <div class="col-md-6">
        <div class="box-element rounded shadow-lg py-2" id="form-wrapper">
            <form action="" id="form">
                {% csrf_token %}
                <div class="p-2" id="user-info">
                    <div class="form-groups d-inline-block" style="width: 48%;">
                        <input required type="text" class="form-control" name="name" placeholder="Name..">
                    </div>
                    <div class="form-groups d-inline-block" style="width: 48%;">
                        <input required type="email" class="form-control" name="email" placeholder="Email..">
                    </div>
                    <!-- <input type="submit" value="continue"> -->
                </div>
                <hr>
                <div id="shipping-info" class="p-2">
                    <p>Shipping Information</p>
                    <div class="form-groups d-inline-block py-1" style="width: 48%">
                        <input type="text" class="form-control" name="address" placeholder="Address..">
                    </div>
                    <div class="form-groups d-inline-block py-1" style="width: 48%">
                        <input type="text" class="form-control" name="city" placeholder="City..">
                    </div>
                    <div class="form-groups d-inline-block py-1" style="width: 48%">
                        <input type="text" class="form-control" name="state" placeholder="State..">
                    </div>
                    <div class="form-groups d-inline-block py-1" style="width: 48%">
                        <input type="text" class="form-control" name="zipcode" placeholder="Zip code..">
                    </div>
                    <!-- <div class="form-groups d-inline-block py-1" style="width: 48%">
                        <input type="text" class="form-control" name="address" placeholder="Address..">
                    </div> -->
                    <div class="form-groups d-inline-block py-1" style="width: 48%">
                        <input type="text" class="form-control" name="country" placeholder="Country..">
                    </div>
                </div>
                <hr>
                <input type="submit" value="continue" id="form-button" class="btn btn-success btn-block">
            </form>
        </div>
        <br>
        <div class="box-element rounded shadow-lg p-2 d-none" id="payment-info">
            <small>paypal options</small>
            <button class="btn btn-outline-info" id="make-payment">Make Payment</button>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box-element rounded shadow-lg p-2">
            <a href="{% url 'store:cart' %}" class="btn btn-outline-dark">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for item in items %}
            <div class="d-flex">
                <div style="flex:2;"><img width="70px" src="{{ item.product.image.url }}" alt="PlaceHolder"></div>
                <div style="flex:2;">{{ item.product.name }}</div>
                <div style="flex:1;">${{ item.product.price|floatformat:2 }}</div>
                <div style="flex:1;">x{{ item.quantity }}</div>
            </div>
            {% endfor %}
            <h5>Items:  {{ order.get_total_items }}</h5>
            <h5>Total:  ${{ order.get_total_price|floatformat:2 }}</h5>
        </div>
    </div>
</div>
<script type="text/javascript">
    let shipping = "{{ order.shipping }}";
    let total = "{{ order.get_total_items }}"
    let csrftoken = document.getElementsByTagName("input")[0].value;
    console.log("shipping ==>" + shipping);
    if (shipping == "False"){
        document.getElementById("shipping-info").innerHTML = "";
    }
    if (user != "AnonymousUser"){
        document.getElementById("user-info").innerHTML = ""
    }

    if (shipping == "False" && user != "AnonymousUser"){
        document.getElementById("form-wrapper").classList.add("d-none");
        document.getElementById("payment-info").classList.remove("d-none");
    }
    let form = document.getElementById("form");

    function submitFormData(){
        console.log("payment button clicked");
        let userFormData = {
            "name": null,
            "email": null,
            "total": total
        }
        let shippingInfo = {
            "address": null,
            "city": null,
            "state": null,
            "zipcode": null,
        }

        if(shipping != "False"){
            shippingInfo.address = form.address.value;
            shippingInfo.city = form.city.value;
            shippingInfo.state = form.state.value;
            shippingInfo.zipcode = form.zipcode.value;
        }
        if(user == "AnonymousUser"){
            userFormData.name = form.name.value;
            userFormData.email = form.email.value;
        }
        let url = "/process_order"
        fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            },
            body: JSON.stringify({"form":userFormData, "shipping": shippingInfo})
        })
        .then((response) => response.json())
        .then((data) => {
            console.log("Success" + data);
            alert("Transaction Completed");
            cart = {}
            document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/";
            window.location.href = "{% url 'store:store' %}";
        })
        }

    form.addEventListener("submit", function(e){
        e.preventDefault();
        console.log("Form submitted");
        document.getElementById("form-button").classList.add("d-none");
        document.getElementById("payment-info").classList.remove("d-none");
        document.getElementById("make-payment").addEventListener("click", function(e){
            
            submitFormData()
        });
    });

</script>
{% endblock %}

store/templates/store/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/detailpage.css' %}">
    <script type="text/javascript">
        let user = '{{ request.user }}'
        function getToken(name){
            let cookieValue = null;
            if(document.cookie && document.cookie !== ""){
                let cookies = document.cookie.split(";");
                for(let i=0; i<cookies.length; i++){
                    let cookie = cookies[i].trim();
                    // Does this cookie begin with the name we want
                    if(cookie.substring(0, name.length + 1) === (name + "=")){
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        // let csrftoken = getToken("csrftoken");

        function getCookie(name){
            // split the string and get all individual name:value pairs in an array
            let cookieArr = document.cookie.split(";")
            // loop through the array elements
            for (let i=0; i<cookieArr.length; i++){
                let cookiePair = cookieArr[i].split("=");
                if(name == cookiePair[0].trim()){
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            // return null if not found
            return null;
        }
        let cart = JSON.parse(getCookie("cart"));
        if(cart == undefined){
            cart = {};
            console.log("cart was created");
            document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/";
        }
        console.log(cart);
    </script>
    <title>Ecom</title>
</head>
<body>
    <!-- <h1>Navbar</h1> -->
    <nav class="navbar navbar-dark navbar-expand-sm bg-primary">
        <a href="{% url 'store:home' %}" class="navbar-brand">Hydra</a>
        <button class="navbar-toggler" data-target="#ToggleNav" data-toggle="collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="ToggleNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{%  url 'store:store' %}" class="nav-link">store</a>
                </li>
            </ul>
            <ul class="navbar-nav my-2 my-lg-0">
                <li class="nav-item">
                    <li class="nav-item">
                        <a href="#" class="nav-link btn rounded btn-warning">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'store:cart' %}">
                            <img src="{% static 'images/cart.png' %}" alt="cart image" style="width: 25px; display: inline-block; margin-left: 15px;">
                        </a>
                        <span class="badge badge-pills badge-light">{{cart_items}}</span>
                    </li>
                    <!-- <li class="nav-item"> -->
                    <!-- </li>  -->
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>
</body>
</html>

store/templates/store/product_detail.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<main>
		<section id="firstsection">
			<div class="containers">
				<div class="row1">
					<div class="leftside">
						<img src="{{ product.image.url }}" class="img-fluids">
					</div>
					<div class="rightside">
						<div class="topbtn">
							<a href="{% url 'store:store' %}" class="btn show">back</a>
						</div>
						<p><del>$200</del> ${{ product.price }}</p>
                        {% if product.description %}
						<h4>Description</h4>
						<p>{{ product.description }}
						</p>
                        {% endif %}
						<div class="buttons">
							<!-- <span>1</span> -->
							<input type="text" value="{{ cart_items }}" disabled="" class="btn">
							<button class=" btn btn-primary update-cart" data-action="add" data-product="{{ product.id }}">add to cart</button>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section id="sectionsection">
			<div class="containers">
				<div class="content">
					<div class="head">
                        {% if product.additional_info %}
						    <h5>Additional information</h5>
						    <p>{{product.additional_info}}
                        {% endif %}
						</p>
					</div>
                    {% if product.other_images %}
                        <h4 class="text-center mb-4">Other Product Images</h4>
                    {% endif %}
					<div class="showcased">
                        {% if product.sub_image1 %}
						<div class="imgs">
							<img src="{{ product.sub_image1.url }}" class="img-fluid" alt="">
						</div>
                        {% endif %}
						{% if product.sub_image2 %}
						<div class="imgs">
							<img src="{{ product.sub_image2.url }}" class="img-fluid" alt="">
						</div>
                        {% endif %}
						{% if product.sub_image3 %}
						<div class="imgs">
							<img src="{{ product.sub_image3.url }}" class="img-fluid" alt="">
						</div>
                        {% endif %}
					</div>
				</div>
			</div>
		</section>
	</main>
    {% endblock %}

store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<h1 class="text-success text-center">Store</h1>
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 col-sm-6 px-2">
            <img class="img-fluid" src="{{ product.image.url }}" alt="Placeholder image">
            <div class="shadow-lg rounded p-3">
                <h5><strong>{{ product.name }}</strong></h5>
                <hr>
                <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-dark update-cart add-btn update-cart">Add to Cart</button>
                <a href="{% url 'store:product_detail' pk=product.pk %}" class="btn btn-outline-success">View</a>
                <h4 class="d-inline-block float-right">${{ product.price|floatformat:2 }}</h4>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}